spring:
  application:
    name: kafka-listener
  kafka:
    consumer:
      bootstrap-servers: "localhost:29092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8081
